#!/usr/bin/env python3
"""Generates Foundry's brand drawables (Android vector XML) into android/overlay/.

The logo is the name itself: a bold "F" monogram for square icons and the word "Foundry" for wordmarks.
Letters are converted to vector paths from a font, since Android vector drawables cannot render text.

Usage: pip install fonttools && python3 android/branding/generate.py [path/to/Bold.ttf]
"""

import sys
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

BRAND = "#2B50E0"
WHITE = "#FFFFFF"
FONT = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

ROOT = Path(__file__).resolve().parent.parent / "overlay" / "mobile/android/fenix/app/src"
HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by android/branding/generate.py. Do not edit by hand. -->
"""

font = TTFont(FONT)
glyphs = font.getGlyphSet()
cmap = font.getBestCmap()


def _measured_cap_height():
    pen = BoundsPen(glyphs)
    glyphs[cmap[ord("H")]].draw(pen)
    return pen.bounds[3]


def text_path(text, height, x=0.0, y=0.0):
    """Path data for `text` whose cap height is `height`, top-left at (x, y). Returns (path, width)."""
    units_cap = getattr(font["OS/2"], "sCapHeight", 0) or _measured_cap_height()
    scale = height / units_cap
    pen = SVGPathPen(glyphs)
    bounds = BoundsPen(glyphs)
    cursor = 0.0
    for ch in text:
        name = cmap[ord(ch)]
        # Font units are y-up; Android vectors are y-down.
        transform = (scale, 0, 0, -scale, x + cursor * scale, y + height)
        glyphs[name].draw(TransformPen(pen, transform))
        glyphs[name].draw(TransformPen(bounds, (1, 0, 0, 1, cursor, 0)))
        cursor += glyphs[name].width
    x_min, _, x_max, _ = bounds.bounds
    return pen.getCommands(), (x_max - x_min) * scale, x_min * scale


def vector(width_dp, height_dp, vw, vh, paths):
    body = "\n".join(
        f'    <path\n        android:fillColor="{color}"\n        android:pathData="{data}" />' for color, data in paths
    )
    return (
        HEADER
        + f'<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{width_dp}dp"\n    android:height="{height_dp}dp"\n'
        f'    android:viewportWidth="{vw:g}"\n    android:viewportHeight="{vh:g}">\n{body}\n</vector>\n'
    )


def rounded_square(size, radius):
    r, s = radius, size
    return (
        f"M{r},0 H{s - r} A{r},{r} 0 0 1 {s},{r} V{s - r} A{r},{r} 0 0 1 {s - r},{s} "
        f"H{r} A{r},{r} 0 0 1 0,{s - r} V{r} A{r},{r} 0 0 1 {r},0 Z"
    )


def centered_f(size, cap):
    _, width, left = text_path("F", cap)
    x = (size - width) / 2 - left
    path, _, _ = text_path("F", cap, x=x, y=(size - cap) / 2)
    return path


def write(rel, content):
    path = ROOT / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print("wrote", path.relative_to(ROOT.parents[4]))


# Square logo: white F on a brand-blue rounded square. Replaces Firefox's logo wherever it appears in the UI.
logo = vector(108, 108, 108, 108, [(BRAND, rounded_square(108, 24)), (WHITE, centered_f(108, 60))])
for rel in [
    "main/res/drawable/foundry_logo.xml",
    "main/res/drawable/ic_firefox.xml",
    "debug/res/drawable/ic_firefox.xml",
    "main/res/drawable/ic_splash_logo.xml",
    "main/res/drawable/expressive_firefox.xml",
]:
    write(rel, logo)

# Launcher icon foreground: white F sized for the adaptive icon's 66dp safe zone (background colour set separately).
foreground = vector(108, 108, 108, 108, [(WHITE, centered_f(108, 40))])
for rel in ["main/res/drawable/ic_launcher_foreground.xml", "debug/res/drawable/ic_launcher_foreground.xml"]:
    write(rel, foreground)

# Single-colour F for themed launcher icons and the notification icon (Android tints these itself).
write("main/res/drawable/ic_launcher_monochrome.xml", vector(108, 108, 108, 108, [(WHITE, centered_f(108, 40))]))
write("main/res/drawable/ic_status_logo.xml", vector(24, 24, 24, 24, [(WHITE, centered_f(24, 18))]))

# Wordmark: "Foundry" in the theme's text colour, so it reads on light and dark backgrounds.
def wordmark(text, cap):
    """Path for `text` fitted tightly to its ink, including ascenders and descenders."""
    bounds = BoundsPen(glyphs)
    cursor = 0
    for ch in text:
        glyphs[cmap[ord(ch)]].draw(TransformPen(bounds, (1, 0, 0, 1, cursor, 0)))
        cursor += glyphs[cmap[ord(ch)]].width
    x_min, y_min, x_max, y_max = bounds.bounds
    scale = cap / (getattr(font["OS/2"], "sCapHeight", 0) or _measured_cap_height())
    pen = SVGPathPen(glyphs)
    cursor = 0
    for ch in text:
        transform = (scale, 0, 0, -scale, (cursor - x_min) * scale, y_max * scale)
        glyphs[cmap[ord(ch)]].draw(TransformPen(pen, transform))
        cursor += glyphs[cmap[ord(ch)]].width
    return pen.getCommands(), (x_max - x_min) * scale, (y_max - y_min) * scale


path, width, height = wordmark("Foundry", 36.0)
write(
    "main/res/drawable/foundry_wordmark_text.xml",
    vector(round(24 * width / height, 1), 24, round(width, 2), round(height, 2), [("?attr/colorOnSurface", path)]),
)

write(
    "debug/res/values/colors.xml",
    HEADER + f'<resources>\n    <color name="ic_launcher_background">{BRAND}</color>\n</resources>\n',
)
